# Plugins
set -g @plugin 'omerxx/tmux-floax'

# remap prefix from 'C-b' to 'M-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1              # start indexing windows at 1 instead of 0
set-window-option -g pane-base-index 1 # start indexing panes at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed

# Status bar
set -g status-left-length 100

# Fix tmux color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g xterm-keys on

# Enable mouse mode
#set -g mouse on

# Use vi keys in copy mode
set -g mode-keys vi

# Dim inactive pane
set -g focus-events on
set-hook -g pane-focus-out 'select-pane -P bg=colour0,fg=colour248'
set-hook -g pane-focus-in 'select-pane -P bg=default,fg=default'

# In vi copy mode:
#   v  starts a selection (alias for Space)
#   Space also starts selection
#   Enter copies and exits
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi Space send -X begin-selection
bind-key -T copy-mode-vi Enter send -X copy-selection-and-cancel

## copies selection into both tmux buffer and X clipboard via xclip:
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# switch panes using Alt+direction(vi) 
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# resize pane with Alt-shift+direction(vi)
bind -n M-H resize-pane -L
bind -n M-L resize-pane -R
bind -n M-K resize-pane -U
bind -n M-J resize-pane -D

# split panes
bind -n C-\\ split-window -h #'Ctrl + \'
bind -n C-_ split-window -v #'Ctrl + -'
unbind '"'
unbind %

# Bind floax to Meta(Alt)-t
set -g @floax-bind '-n M-t'

# Load TPM
run '~/.config/tmux/plugins/tpm/tpm'
