monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
	device.profile = "a2dp-sink"
	bluez5.auto-connect = [ "a2dp_sink" ]
        bluez5.hw-volume = [ "a2dp_sink" ]
        bluez5.a2dp.ldac.quality = "auto"
        bluez5.a2dp.aac.bitratemode = 0
        bluez5.a2dp.opus.pro.application = "audio"
        bluez5.a2dp.opus.pro.bidi.application = "audio"        
      }
    }
  }
]
